name: 📃Task Template
description: Use this template when defining a new task in an issue
title: "[TASK] "
labels: ["feature"]

body:
#  - type: input
#    attributes:
#      label: Time estimate (Hours)
#      description: Fill in the estimated time for the task.
#      placeholder: |
#        HH (Hours)
#    validations:
#      required: true

#  - type: input
#    attributes:
#      label: Deadline (DD.MM)
#      description: Specify the deadline for the task.
#      placeholder: |
#       DD.MM (Day.Month)
#    validations:
#      required: true

  - type: textarea
    attributes:
      label: Description of task
      description: Provide a detailed description of the task.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Specifications
      description: List any specific requirements or specifications for the task.
      placeholder: |
        - Spec 1
        - Spec 2
        - Spec 3

  - type: textarea
    attributes:
      label: Suggested Workflow
      description: Outline the suggested steps to complete the task.
      placeholder: |
        - Step 1
        - Step 2
        - Step 3

  - type: textarea
    attributes:
      label: Contacts
      description: Provide any relevant contacts for this task (e.g., team members, mentors).
      placeholder: |
        - Name - Member/Mentor, knows this and that


